#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# autojump
[[ -s /etc/profile.d/autojump.sh ]] && source /etc/profile.d/autojump.sh

alias ls='ls --color=auto'
PS1='[\W]\$ '

# fzf key bindings
source /usr/share/fzf/key-bindings.bash
source /usr/share/fzf/completion.bash

# required for GPG to be able to prompt for a passphrase
export GPG_TTY=$(tty)

export GOPATH="$HOME/go"
export PATH="$PATH:$HOME/.local/bin:$HOME/.scripts:$HOME/.cargo/bin:$GOPATH/bin"

if [ -f ~/.bashrc_ext ]; then
    . ~/.bashrc_ext
fi

if [ -f ~/.bash_functions ]; then
    . ~/.bash_functions
fi

if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi

export XDG_CONFIG_HOME="$HOME/.config"

# bash history settings
export HISTSIZE=100000
export HISTFILESIZE=$HISTSIZE
export HISTCONTROL=ignoredups:erasedups:ignorespace
shopt -s histappend
