local dap = require("dap")
local go_dap = require("go.dap")

vim.keymap.set("n", "<leader>dr", go_dap.run)
vim.keymap.set("n", "<leader>dc", dap.continue)
vim.keymap.set("n", "<leader>dn", dap.step_over)
vim.keymap.set("n", "<leader>ds", dap.step_into)
vim.keymap.set("n", "<leader>do", dap.step_out)
vim.keymap.set("n", "<leader>dS", dap.stop)
vim.keymap.set("n", "<leader>du", dap.up)
vim.keymap.set("n", "<leader>dd", dap.down)
vim.keymap.set("n", "<leader>dC", dap.run_to_cursor)
vim.keymap.set("n", "<leader>db", dap.toggle_breakpoint)
vim.keymap.set("n", "<leader>dP", dap.pause)
